#!/bin/bash

echo "🚀 Setting up GitHub Actions for FindBrexitConsultants.co.uk"
echo "=================================================="

# Step 1: Push to GitHub
echo ""
echo "📤 STEP 1: Push code to GitHub"
echo "--------------------------------"
echo "Your code is ready to push to GitHub. Run these commands:"
echo ""
echo "cd /workspace/findbrexit-consultants"
echo "git push -u origin master"
echo ""
echo "If you encounter authentication issues:"
echo "1. Use GitHub CLI: gh auth login"
echo "2. Or generate a Personal Access Token from GitHub Settings"
echo "3. Or use SSH keys for authentication"
echo ""

# Step 2: Configure Secrets
echo "🔐 STEP 2: Configure GitHub Repository Secrets"
echo "----------------------------------------------"
echo "Go to: https://github.com/mitchell1972/findbrexitconsultants/settings/secrets/actions"
echo ""
echo "Add these secrets for VERCEL deployment:"
echo "• VERCEL_TOKEN"
echo "• VERCEL_ORG_ID"  
echo "• VERCEL_PROJECT_ID"
echo ""
echo "Add these secrets for HOSTINGER deployment:"
echo "• HOSTINGER_FTP_HOST"
echo "• HOSTINGER_FTP_USERNAME"
echo "• HOSTINGER_FTP_PASSWORD"
echo "• VITE_SUPABASE_URL"
echo "• VITE_SUPABASE_ANON_KEY"
echo ""

# Step 3: Get Vercel Credentials
echo "🔧 STEP 3: Get Vercel Credentials"
echo "---------------------------------"
echo "1. VERCEL_TOKEN:"
echo "   → Go to https://vercel.com/account/tokens"
echo "   → Create a new token"
echo "   → Copy the token value"
echo ""
echo "2. VERCEL_ORG_ID and VERCEL_PROJECT_ID:"
echo "   → Run 'vercel link' in your project locally"
echo "   → Check .vercel/project.json for both IDs"
echo ""

# Step 4: Get Hostinger Credentials
echo "🌐 STEP 4: Get Hostinger FTP Credentials"
echo "---------------------------------------"
echo "1. Login to Hostinger Control Panel"
echo "2. Go to File Manager → FTP Access"
echo "3. Get/Create FTP credentials:"
echo "   • Host: Usually ftp.yourdomain.com"
echo "   • Username: Your FTP username"
echo "   • Password: Your FTP password"
echo ""

# Step 5: Test Deployment
echo "✅ STEP 5: Test Deployment"
echo "-------------------------"
echo "After setting up secrets:"
echo "1. Make a small change to your code"
echo "2. Commit and push: git add . && git commit -m 'Test deployment' && git push"
echo "3. Check GitHub Actions tab for deployment status"
echo "4. Verify sites are live:"
echo "   • Vercel: [Preview URL from deployment]"
echo "   • Hostinger: https://FindBrexitConsultants.co.uk"
echo ""

echo "🎉 Setup Complete!"
echo "=================="
echo "Your GitHub Actions are configured for:"
echo "✓ Automatic Vercel deployment"
echo "✓ Automatic Hostinger deployment"  
echo "✓ Dual hosting redundancy"
echo "✓ Production-optimized builds"
echo ""
echo "Documentation available:"
echo "• GITHUB_DEPLOYMENT_README.md"
echo "• HOSTINGER_GITHUB_ACTIONS_SETUP.md"
echo "• DUAL_DEPLOYMENT_GUIDE.md"
