#!/bin/bash

# Complete Deployment Script for FindBrexit Consultants
# Repository: https://github.com/mitchell1972/findbrexitconsultants
# This script contains all the commands to deploy your application

echo "🚀 FindBrexit Consultants - Complete Deployment Guide"
echo "===================================================="
echo "Repository: https://github.com/mitchell1972/findbrexitconsultants"
echo ""

echo "📋 STEP 1: Push to GitHub"
echo "========================="
echo "Run these commands in your local project directory:"
echo ""
echo "# Navigate to your project (if not already there)"
echo "cd /path/to/findbrexit-consultants"
echo ""
echo "# Verify git status"
echo "git status"
echo ""
echo "# Add remote origin (if not already added)"
echo "git remote add origin https://github.com/mitchell1972/findbrexitconsultants.git"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""

echo "📋 STEP 2: Set up Vercel Project"
echo "================================="
echo "1. Go to https://vercel.com"
echo "2. Click 'New Project'"
echo "3. Import from GitHub: mitchell1972/findbrexitconsultants"
echo "4. Framework: Vite (should auto-detect)"
echo "5. Build Command: npm run build"
echo "6. Output Directory: dist"
echo "7. Install Command: npm install"
echo ""

echo "📋 STEP 3: Add Environment Variables in Vercel"
echo "=============================================="
echo "In Vercel Dashboard → Project → Settings → Environment Variables"
echo "Add these for all environments (Production, Preview, Development):"
echo ""
echo "VITE_SUPABASE_URL=https://zjfilhbczaquokqlcoej.supabase.co"
echo "VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZmlsaGJjemFxdW9rcWxjb2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQ2MjIsImV4cCI6MjA3MTExMDYyMn0.b6YATor8UyDwYSiSagOQUxM_4sqfCv-89CBXVgC2hP0"
echo "VITE_STRIPE_PUBLISHABLE_KEY=[Your Stripe Key - if using Stripe]"
echo ""

echo "📋 STEP 4: Get Vercel Credentials for GitHub Actions"
echo "===================================================="
echo "You'll need these three values from Vercel:"
echo ""
echo "1. VERCEL_TOKEN:"
echo "   - Go to Vercel Dashboard → Settings → Tokens"
echo "   - Create token named 'GitHub Actions Token'"
echo ""
echo "2. VERCEL_ORG_ID:"
echo "   - Vercel Dashboard → Settings → General → Team ID"
echo ""
echo "3. VERCEL_PROJECT_ID:"
echo "   - Your Project → Settings → General → Project ID"
echo ""

echo "📋 STEP 5: Add GitHub Secrets"
echo "============================="
echo "Go to: https://github.com/mitchell1972/findbrexitconsultants/settings/secrets/actions"
echo ""
echo "Add these Repository Secrets:"
echo "- VERCEL_TOKEN: [From Step 4.1]"
echo "- VERCEL_ORG_ID: [From Step 4.2]"
echo "- VERCEL_PROJECT_ID: [From Step 4.3]"
echo ""

echo "📋 STEP 6: Test Automatic Deployment"
echo "===================================="
echo "After setting up GitHub secrets, test the automation:"
echo ""
echo "# Make a small change"
echo "echo '# Test deployment' >> README.md"
echo ""
echo "# Commit and push"
echo "git add ."
echo "git commit -m 'Test automatic deployment'"
echo "git push origin main"
echo ""
echo "✅ This should trigger automatic deployment to Vercel!"
echo ""

echo "📋 STEP 7: Configure Custom Domain (Optional)"
echo "============================================="
echo "In Vercel Dashboard → Your Project → Settings → Domains:"
echo "1. Add: findbrexitconsultants.co.uk"
echo "2. Add: www.findbrexitconsultants.co.uk"
echo ""
echo "Update DNS with your domain provider:"
echo "- A Record: @ → 76.76.19.61"
echo "- CNAME: www → cname.vercel-dns.com"
echo ""

echo "🎉 DEPLOYMENT COMPLETE!"
echo "======================="
echo "After following all steps, you'll have:"
echo "✅ Code pushed to GitHub"
echo "✅ Automatic deployments on every push"
echo "✅ Preview deployments for pull requests"
echo "✅ Production deployment with custom domain"
echo ""
echo "🌐 Your application will be live at:"
echo "   - Vercel URL: [provided after deployment]"
echo "   - Custom Domain: https://findbrexitconsultants.co.uk"
