CREATE TABLE brexit_consultants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    company_name VARCHAR(255) NOT NULL,
    company_logo_url TEXT,
    contact_person VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    website_url TEXT,
    linkedin_url TEXT,
    whatsapp_number VARCHAR(50),
    years_in_business INTEGER DEFAULT 0,
    team_size VARCHAR(50),
    response_time_hours INTEGER DEFAULT 24,
    description TEXT,
    minimum_project_size VARCHAR(50),
    typical_project_duration VARCHAR(100),
    pricing_level INTEGER DEFAULT 1,
    free_consultation BOOLEAN DEFAULT false,
    address TEXT,
    city VARCHAR(100),
    postcode VARCHAR(20),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    verified BOOLEAN DEFAULT false,
    featured BOOLEAN DEFAULT false,
    profile_views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    approved_at TIMESTAMP WITH TIME ZONE,
    approved_by UUID
);